name: gallery_app
description: "Gallery App Flutter as a part of internship project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^8.0.1
  retrofit: ^4.4.1
  injectable: ^2.5.0
  form_field_validator: ^1.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: 4.0.0
  retrofit_generator: 8.2.1
  injectable_generator: ^2.6.2


flutter:
  uses-material-design: true
  generate: true
